// LOCALHOST TESTING

### Get all contacts
GET http://localhost:8080/contacts

### Get a contact by ID
GET http://localhost:8080/contacts/6793f6e46a25a6453b0a0511

### Create a new contact
POST http://localhost:8080/contacts
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "john.doe@example.com",
    "favoriteColor": "Blue",
    "birthday": "1990-01-01"
}

### Update a contact
PUT http://localhost:8080/contacts/6793f6e46a25a6453b0a0511
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName": "Smith",
    "email": "jane.smith@example.com",
    "favoriteColor": "Red",
    "birthday": "1995-05-15"
}

### Delete a contact
DELETE http://localhost:8080/contacts/6792a3098cb3a22c06d35611

